name: dummy

director_uuid: 65810174-b70b-4278-b988-7c86e5cf9d5f

releases:
- name: emc_baremetal
  url: file://~/workspace/emc_baremetal/dev_releases/onrack-cpi/onrack-cpi-0+dev.1.tgz
- name: redis
  url: file://~/workspace/emc_baremetal/redis-bosh-release.tgz

networks:
- name: default
  type: manual

  subnets:
  - range: ${IP_RANGE}
    gateway: ${GATEWAY}

    static: [${NODE_IP}]

resource_pools:
- name: default
  network: default
  cloud_properties:
    public_key: ${PUBLIC_KEY}
  stemcell:
    url: file://~/Downloads/bosh-stemcell-3042-vsphere-esxi-ubuntu-trusty-go_agent.tgz

compilation:
  workers: 1
  network: default
  reuse_compilation_vms: true

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000 - 30000
  update_watch_time: 1000 - 30000

jobs:
- name: redis
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips: [${NODE_IP}]
  templates:
  - {name: redis, release: redis}
  properties:
    redis:
      password: r3d!s
      port: 6379

cloud_provider:
  template: {name: onrack-cpi, release: onrack-cpi}

  mbus: https://mbus:Pbc7ssdfh8w2@${NODE_IP}:6868

  properties:
    onrack-cpi:
      apiserver: ${ONRACK_API}
      agent:
        mbus: "https://mbus:Pbc7ssdfh8w2@0.0.0.0:6868"
        blobstore:
          provider: local
          options: {blobstore_path: /var/vcap/micro_bosh/data/cache}
