name: dummy

director_uuid: 65810174-b70b-4278-b988-7c86e5cf9d5f

releases:
- name: emc_baremetal
  url: file://~/workspace/emc_baremetal/dev_releases/emc_baremetal/emc_baremetal-0+dev.1.tgz

networks:
- name: default
  type: dynamic

resource_pools:
- name: default
  network: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
    url: file://~/Downloads/bosh-stemcell-3042-vsphere-esxi-ubuntu-trusty-go_agent.tgz

compilation:
  workers: 1
  network: default
  reuse_compilation_vms: true

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000 - 30000
  update_watch_time: 1000 - 30000

jobs:
- name: first
  templates:
  - {name: baremetal_cpi, release: emc_baremetal}
  instances: 1
  resource_pool: default
  networks:
  - name: default

    static_ips: []

cloud_provider:
  template: {name: baremetal_cpi, release: emc_baremetal}

  mbus: https://mbus:Pbc7ssdfh8w2@{NODE_IP}:6868

#figure out needed baremetal properties
  properties:
    baremetal_cpi:
      machines:
        some-vm: 127.0.0.1
      apiserver: ${BAREMETAL_API}
      stemcells_dir: /Users/elm/.bosh_init/stemcells
      agent:
        mbus: "https://mbus:Pbc7ssdfh8w2@0.0.0.0:6868"
        blobstore:
          provider: local
          options: {blobstore_path: /var/vcap/micro_bosh/data/cache}
        disks:
          system: "/dev/sda"
          ephemeral: "/dev/sdb"
          persistent: {}
      private_key: &private_key |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEpAIBAAKCAQEA433I7+JP1TvcqOhF2P6sVPpLb6L1IFBVt95zY0TnLyVbnwbU
          L6dhiT2o5vOGPNXTboV65s6F2o8YiH05Bha0x8VoMWokEHkV82UU60FCrwhLTFkj
          ..snip..
          po8qXz8/p+cXF0FTX49117jrr/ZnKAVlxkcgH6ImwoA9eQdHnDNs/w==
          -----END RSA PRIVATE KEY-----