---
groups:
  - name: bosh-rackhd-cpi
    jobs:
      - integration
      - lifecycle

jobs:
- name: integration
  serial: true
  plan:
  - aggregate:
    - {trigger: true, get: bosh-cpi-release,     resource: bosh-cpi-release-in}

  - task: test
    file: bosh-cpi-release/ci/tasks/integration.yml
    config:
      params:
        RACKHD_API_URI:              {{rackhd_server_ip}}

- name: lifecycle
  serial: true
  plan:
  - aggregate:
    - {trigger: true,  passed: [integration],  get: bosh-cpi-release,   resource: bosh-cpi-release-in}
    - {trigger: false,                         get: stemcell,           resource: rackhd-openstack-stemcell}
  - task: test
    file: bosh-cpi-release/ci/tasks/lifecycle.yml
    config:
      params:
        RACKHD_API_URI:              {{rackhd_server_ip}}
        AGENT_PUBLIC_KEY:             {{agent_publick_key}}
        STATIC_IP:                    {{static_ip}}
        GATEWAY:                      {{gateway}}

resources:
- name: bosh-cpi-release-in
  type: git
  source:
    uri: git@github.com:EMC-CMD/bosh-rackhd-cpi-release.git
    branch: master
    private_key: {{github_deployment_key__bosh-rackhd-cpi-release}}
    ignore_paths:
      - .final_builds/**/*.yml
      - releases/**/*.yml

- name: rackhd-openstack-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent-raw
