---
groups:
  - name: bosh-rackhd-cpi
    jobs:
      - integration
      - lifecycle
      - bats-virtual

jobs:
- name: integration
  serial: true
  plan:
  - aggregate:
    - {trigger: true, get: bosh-cpi-release,     resource: bosh-rackhd-cpi-release}

  - task: test
    file: bosh-cpi-release/ci/tasks/integration.yml
    config:
      params:
        RACKHD_API_URI:              {{rackhd_server_ip}}

- name: lifecycle
  serial: true
  plan:
  - aggregate:
    - {trigger: true,  passed: [integration],  get: bosh-cpi-release,   resource: bosh-rackhd-cpi-release}
    - {trigger: false,                         get: stemcell,           resource: rackhd-openstack-stemcell}
  - task: test
    file: bosh-cpi-release/ci/tasks/lifecycle.yml
    config:
      params:
        RACKHD_API_URI:               {{rackhd_server_ip}}
        AGENT_PUBLIC_KEY:             {{agent_public_key}}
        STATIC_IP:                    {{static_ip}}
        GATEWAY:                      {{gateway}}

- name: bats-virtual
  serial: true
  plan:
  - aggregate:
    - {trigger: true,  passed: [lifecycle],   get: bosh-cpi-release,   resource: bosh-rackhd-cpi-release}
    - {trigger: false, passed: [lifecycle],   get: stemcell,           resource: rackhd-openstack-stemcell}
    - {trigger: false,                        get: bats,               resource: bosh-acceptance-tests}
  - task: test
    file: bosh-cpi-release/ci/tasks/lifecycle.yml
    config:
      params:
        PRIVATE_KEY:                        {{agent_private_key}}
        PUBLIC_KEY:                         {{agent_public_key}}
        BOSH_DIRECTOR_PUBLIC_IP:            {{virtual_bosh_director_public_ip}}
        BOSH_DIRECTOR_PRIVATE_IP:           {{virtual_bosh_director_private_ip}}
        SECONDARY_STATIC_IP:                {{virtual_secondary_static_ip}}
        PRIMARY_NETWORK_CIDR:               {{virtual_primary_network_cidr}}
        PRIMARY_NETWORK_GATEWAY:            {{virtual_primary_network_gateway}}
        PRIMARY_NETWORK_RANGE:              {{virtual_primary_network_range}}
        PRIMARY_NETWORK_MANUAL_IP:          {{virtual_primary_network_manual_ip}}

resources:
- name: bosh-rackhd-cpi-release
  type: git
  source:
    uri: git@github.com:EMC-CMD/bosh-rackhd-cpi-release.git
    branch: master
    private_key: {{github_key__bosh-rackhd-cpi-release}}
    ignore_paths:
      - .final_builds/**/*.yml
      - releases/**/*.yml

- name: rackhd-openstack-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent-raw

- name: bosh-acceptance-tests
  type: git
  source:
    uri: git@github.com:EMC-CMD/bosh-acceptance-tests.git
    branch: wip-branch
    private_key: {{github_key__bosh-acceptance-tests}}
