---
groups:
  - name: bosh-onrack-cpi
    jobs:
      - integration
      - lifecycle

jobs:
- name: integration
  serial: true
  plan:
  - aggregate:
    - {trigger: true, get: bosh-cpi-release,     resource: bosh-cpi-release-in}

  - task: test
    file: bosh-cpi-release/ci/tasks/integration.yml
    config:
      params:
        ON_RACK_API_URI:              {{onrack_server_ip}}

- name: lifecycle
  serial: true
  plan:
  - aggregate:
    - {trigger: true,  passed: [integration],  get: bosh-cpi-release,   resource: bosh-cpi-release-in}
    - {trigger: false,                         get: stemcell,           resource: onrack-openstack-stemcell}
  - task: test
    file: bosh-cpi-release/ci/tasks/lifecycle.yml
    config:
      params:
        ON_RACK_API_URI:              {{onrack_server_ip}}
        AGENT_PUBLIC_KEY:             {{agent_publick_key}}
        STATIC_IP:                    {{static_ip}}
        GATEWAY:                      {{gateway}}

resources:
- name: bosh-cpi-release-in
  type: git
  source:
    uri: git@github.com:Pipe-s/emc_baremetal.git
    branch: master
    private_key: {{github_deployment_key__bosh-onrack-cpi-release}}
    ignore_paths:
      - .final_builds/**/*.yml
      - releases/**/*.yml

- name: onrack-openstack-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent-raw
